apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "token"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
spec:
  rules:
   - http:
      paths:
      - path: /api
        backend:
          serviceName: richie-backend
          servicePort: 3000
      - path: /
        backend:
          serviceName: richie-frontend
          servicePort: 80

